### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by fkromer** [davetcoleman/ros2_experimental#2]
When building with `docker build -t ros2-exp .` (which pulls the current ros2 repos) the docker build fails:

```
Step 24/25 : RUN src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install
 ---> Running in eb838c8181c2
Traceback (most recent call last):
  File "src/ament/ament_tools/scripts/ament.py", line 140, in <module>
    from ament_tools.package_types.cmake import entry_point_data as cmake_entry_point_data  # noqa
  File "/root/ws_ros2/src/ament/ament_tools/ament_tools/package_types/cmake.py", line 18, in <module>
    from ament_package.dependency import Dependency
  File "/root/ws_ros2/src/ament/ament_package/ament_package/dependency.py", line 15, in <module>
    from ament_package.condition import evaluate_condition
  File "/root/ws_ros2/src/ament/ament_package/ament_package/condition.py", line 17, in <module>
    import pyparsing
ImportError: No module named 'pyparsing'
The command '/bin/sh -c src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install' returned a non-zero code: 1
```

**Comment by fkromer** [comment]
After adding the installation of `pyparsing` the installation fails due to the `rviz_ogre_vendor` 

```
CMake Error at CMake/Utils/MacroLogFeature.cmake:100 (MESSAGE):
  

  
  -----------------------------------------------------------------------------


  -- The following REQUIRED packages could NOT be located on your system.

  -- Please install them before continuing this software installation.

  -- If you are in Windows, try passing -DOGRE_DEPENDENCIES_DIR=<path to
  dependencies>

  
  -----------------------------------------------------------------------------


  + Xaw: X11 Athena widget set <http://www.x.org>

  
  -----------------------------------------------------------------------------
Call Stack (most recent call first):
  CMake/Dependencies.cmake:399 (MACRO_DISPLAY_FEATURE_LOG)
  CMakeLists.txt:352 (include)


-- Configuring incomplete, errors occurred!
See also "/root/ws_ros2/build/rviz_ogre_vendor/ogre-master-ca665a6-prefix/src/ogre-master-ca665a6-build/CMakeFiles/CMakeOutput.log".
See also "/root/ws_ros2/build/rviz_ogre_vendor/ogre-master-ca665a6-prefix/src/ogre-master-ca665a6-build/CMakeFiles/CMakeError.log".
make[2]: *** [ogre-master-ca665a6-prefix/src/ogre-master-ca665a6-stamp/ogre-master-ca665a6-configure] Error 1
CMakeFiles/ogre-master-ca665a6.dir/build.make:108: recipe for target 'ogre-master-ca665a6-prefix/src/ogre-master-ca665a6-stamp/ogre-master-ca665a6-configure' failed
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ogre-master-ca665a6.dir/all' failed
make[1]: *** [CMakeFiles/ogre-master-ca665a6.dir/all] Error 2
make: *** [all] Error 2
Makefile:138: recipe for target 'all' failed
<== Command '. /root/ws_ros2/build/rviz_ogre_vendor/cmake__build.sh && /usr/bin/make -j4 -l4' failed in '/root/ws_ros2/build/rviz_ogre_vendor' with exit code '2'

<== Command '. /root/ws_ros2/build/rviz_ogre_vendor/cmake__build.sh && /usr/bin/make -j4 -l4' failed in '/root/ws_ros2/build/rviz_ogre_vendor' with exit code '2'
The command '/bin/sh -c src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install' returned a non-zero code: 1
```
